#!/bin/sh
while getopts "i:s:d:o:p:" option;
do 
case $option in
i)
spec_file="$OPTARG";;
s)
strategy="$OPTARG";;
d)
maxdepth="$OPTARG";;
o)
output="$OPTARG";;
p)
projection="-sp";;
esac
done

make clean >> /dev/null
echo
echo "_________________________________________________________________"
echo  " TestGen-IFx Tool."
echo "_________________________________________________________________"
echo ""
echo "_________________________________________________________________"
echo "Status: Compiling $spec_file.if file ..."

make "$spec_file.g" >> /dev//null 

echo "_________________________________________________________________"
echo "Status: Generating test case ..."

touch "./output.sequence"

echo "_________________________________________________________________" >> "output.stat"
echo  " TestGen-IF Tool Statistics." >> "output.stat"
echo "_________________________________________________________________" >> "output.stat"
echo "" >> "output.stat"
echo "	IF specification: $spec_file.if"  >> "output.stat"
echo "	Strategy: $strategy" >> "output.stat"
echo "	Depth limit: $maxdepth" >> "output.stat"

#echo "$spec_file.g -$strategy -d $maxdepth -o $output  $projection"

./$spec_file.g -$strategy -d $maxdepth -o $output  $projection

echo "_________________________________________________________________"
echo "	>>> 	output.sequence file for test sequence"
echo "	>>> 	output.stat file for statistics"
echo "_________________________________________________________________"
echo ""

echo "" >> "output.stat"
echo "	Test case length: $(wc -l ./output.sequence | cut -d" " -f1)" >> "output.stat"
echo " 	Test generation duration: $hours:$minutes:$seconds" >> "output.stat"
echo "_________________________________________________________________" >> "output.stat"
